export const SESSION_EVENTS = Object.freeze({
  CREATED: "SESSION_CREATED",
  STARTED: "SESSION_STARTED",
  REPLAY_UPDATED: "REPLAY_UPDATED",
  DECISION_RECORDED: "DECISION_RECORDED",
  TRADE_UPDATED: "TRADE_UPDATED",
  TRADE_SUBMITTED: "TRADE_SUBMITTED",
  TRADE_GRADED: "TRADE_GRADED",
  COACH_RECORDED: "COACH_RECORDED",
  ACHIEVEMENT_UNLOCKED: "ACHIEVEMENT_UNLOCKED",
  COMPLETED: "SESSION_COMPLETED",
  ABANDONED: "SESSION_ABANDONED",
});

export default SESSION_EVENTS;
